# Netlify Configuration for Multiagent Development Platform

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; worker-src 'self' blob:;"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Vector database endpoints
[[redirects]]
  from = "/api/vectors/store"
  to = "/.netlify/functions/vector-store"
  status = 200

[[redirects]]
  from = "/api/vectors/search"
  to = "/.netlify/functions/vector-store"
  status = 200

[[redirects]]
  from = "/api/vectors/embed"
  to = "/.netlify/functions/vector-store"
  status = 200

[[redirects]]
  from = "/api/vectors/health"
  to = "/.netlify/functions/vector-store"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  autoLaunch = false

# Edge Functions for enhanced performance
[[edge_functions]]
  function = "agent-processor"
  path = "/api/agents/*"

[[edge_functions]]
  function = "data-scraper"
  path = "/api/scrape/*"

[[edge_functions]]
  function = "vector-store"
  path = "/api/vectors/*"